from tkinter import *
window =Tk()
window.title("basic_modification_tk")
window.geometry("500x700")
window.config(bg="lightblue")
frame1 = Frame(window,width=300,height=300,cursor="dot")
frame2 = Frame(window,width=300,height=300,cursor="dotbox")
button1 =Button(frame1, text="Click",bg="green")
button2 =Button(frame2, text="Press",bg="red")
button3 =Button(frame1, text="Submit",fg="orange")
frame1.pack(side=TOP)
frame2.pack(side=BOTTOM)
button1.pack()
button2.pack()
button3.pack()

window.mainloop()
